"""add created_at to quiz_attempts

Revision ID: 1e8d6f55d7b4
Revises: d19a3f3d7361
Create Date: 2026-06-20 15:11:26.568745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8d6f55d7b4'
down_revision: Union[str, Sequence[str], None] = 'd19a3f3d7361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'created_at')
    # ### end Alembic commands ###
