"""remove unused topic column

Revision ID: 764378ea7fd3
Revises: 1e8d6f55d7b4
Create Date: 2026-07-05 03:04:16.980332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764378ea7fd3'
down_revision: Union[str, Sequence[str], None] = '1e8d6f55d7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'explanation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('questions', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
